safe: true
lsi: false
pygments: true
permalink: /posts/:year/:month/:day/:title
title: "Блог Конфуция"
url: "http://kung-fu-tzu.ru"
author:
    name: Петр Леонов
    email: comments@kung-fu-tzu.ru

en:
  title: "Confucius Blog"
  author:
      name: Peter Leonov
      email: comments@kung-fu-tzu.ru
