keys = %W{
  daemon
  master_process
  timer_resolution
  pid
  lock_file
  worker_processes
  debug_points
  user
  worker_priority
  worker_cpu_affinity
  worker_rlimit_nofile
  worker_rlimit_core
  worker_rlimit_sigpending
  working_directory
  env
  error_log
  include
  events
  worker_connections
  connections
  use
  multi_accept
  accept_mutex
  accept_mutex_delay
  debug_connection
  kqueue_changes
  kqueue_events
  http
  variables_hash_max_size
  variables_hash_bucket_size
  server_names_hash_max_size
  server_names_hash_bucket_size
  server
  connection_pool_size
  request_pool_size
  client_header_timeout
  client_header_buffer_size
  large_client_header_buffers
  optimize_server_names
  ignore_invalid_headers
  merge_slashes
  underscores_in_headers
  location
  listen
  server_name
  types_hash_max_size
  types_hash_bucket_size
  types
  default_type
  root
  alias
  limit_except
  client_max_body_size
  client_body_buffer_size
  client_body_timeout
  client_body_temp_path
  client_body_in_file_only
  client_body_in_single_buffer
  sendfile
  sendfile_max_chunk
  read_ahead
  directio
  directio_alignment
  tcp_nopush
  tcp_nodelay
  send_timeout
  send_lowat
  postpone_output
  limit_rate
  limit_rate_after
  keepalive_timeout
  keepalive_requests
  satisfy
  satisfy_any
  internal
  lingering_time
  lingering_timeout
  reset_timedout_connection
  server_name_in_redirect
  port_in_redirect
  msie_padding
  msie_refresh
  log_not_found
  log_subrequest
  recursive_error_pages
  server_tokens
  if_modified_since
  error_page
  try_files
  post_action
  error_log
  open_file_cache
  open_file_cache_valid
  open_file_cache_retest
  open_file_cache_min_uses
  open_file_cache_errors
  open_file_cache_events
  resolver
  resolver_timeout
  gzip_vary
  gzip_http_version
  gzip_proxied
  gzip_disable
  log_format
  access_log
  open_log_file_cache
  upstream
  server
  autoindex
  autoindex_localtime
  autoindex_exact_size
  index
  auth_basic
  auth_basic_user_file
  allow
  deny
  limit_zone
  limit_conn
  limit_conn_log_level
  limit_req_zone
  limit_req
  limit_req_log_level
  geo
  map
  map_hash_max_size
  map_hash_bucket_size
  valid_referers
  rewrite
  return
  break
  if
  set
  rewrite_log
  uninitialized_variable_warn
  proxy_pass
  proxy_redirect
  proxy_store
  proxy_store_access
  proxy_buffering
  proxy_ignore_client_abort
  proxy_bind
  proxy_connect_timeout
  proxy_send_timeout
  proxy_send_lowat
  proxy_intercept_errors
  proxy_set_header
  proxy_headers_hash_max_size
  proxy_headers_hash_bucket_size
  proxy_set_body
  proxy_method
  proxy_pass_request_headers
  proxy_pass_request_body
  proxy_buffer_size
  proxy_read_timeout
  proxy_buffers
  proxy_busy_buffers_size
  proxy_cache
  proxy_cache_key
  proxy_cache_path
  proxy_cache_valid
  proxy_cache_min_uses
  proxy_cache_use_stale
  proxy_cache_methods
  proxy_temp_path
  proxy_max_temp_file_size
  proxy_temp_file_write_size
  proxy_next_upstream
  proxy_upstream_max_fails
  proxy_upstream_fail_timeout
  proxy_pass_header
  proxy_hide_header
  proxy_ignore_headers
  fastcgi_pass
  fastcgi_index
  fastcgi_split_path_info
  fastcgi_store
  fastcgi_store_access
  fastcgi_ignore_client_abort
  fastcgi_bind
  fastcgi_connect_timeout
  fastcgi_send_timeout
  fastcgi_send_lowat
  fastcgi_buffer_size
  fastcgi_pass_request_headers
  fastcgi_pass_request_body
  fastcgi_intercept_errors
  fastcgi_read_timeout
  fastcgi_buffers
  fastcgi_busy_buffers_size
  fastcgi_cache
  fastcgi_cache_key
  fastcgi_cache_path
  fastcgi_cache_valid
  fastcgi_cache_min_uses
  fastcgi_cache_use_stale
  fastcgi_cache_methods
  fastcgi_temp_path
  fastcgi_max_temp_file_size
  fastcgi_temp_file_write_size
  fastcgi_next_upstream
  fastcgi_upstream_max_fails
  fastcgi_upstream_fail_timeout
  fastcgi_param
  fastcgi_pass_header
  fastcgi_hide_header
  fastcgi_ignore_headers
  fastcgi_catch_stderr
  memcached_pass
  memcached_bind
  memcached_connect_timeout
  memcached_send_timeout
  memcached_buffer_size
  memcached_read_timeout
  memcached_next_upstream
  memcached_upstream_max_fails
  memcached_upstream_fail_timeout
  empty_gif
  modern_browser
  ancient_browser
  modern_browser_value
  ancient_browser_value
  ip_hash
  gzip
  gzip_buffers
  gzip_types
  gzip_comp_level
  gzip_window
  gzip_hash
  postpone_gzipping
  gzip_no_buffer
  gzip_min_length
  charset
  source_charset
  override_charset
  charset_types
  charset_map
  ssi
  ssi_silent_errors
  ssi_ignore_recycled_buffers
  ssi_min_file_chunk
  ssi_value_length
  ssi_types
  userid
  userid_service
  userid_name
  userid_domain
  userid_path
  userid_expires
  userid_p3p
  userid_mark
  expires
  add_header
  output_buffers
  
  perl
  perl_modules
  perl_require
  perl_set
  
  add_before_body
  add_after_body
  addition_types
  
  ancient_browser
  ancient_browser_value
  modern_browser
  modern_browser_value
  
  charset
  charset_map
  charset_types
  override_charset
  source_charset
  
  empty_gif
  
  flv
  
  geo
  
  geoip_country
  geoip_city
  
  gzip_static
  
  image_filter
  image_filter_buffer
  image_filter_jpeg_quality
  image_filter_transparency
  
  dav_access
  dav_methods
  create_full_put_path
  min_delete_depth
  
  random_index
  
  set_real_ip_from
  real_ip_header
  
  ssl
  ssl_certificate
  ssl_certificate_key
  ssl_client_certificate
  ssl_ciphers
  ssl_crl
  ssl_dhparam
  ssl_prefer_server_ciphers
  ssl_protocols
  ssl_verify_client
  ssl_verify_depth
  ssl_session_cache
  ssl_session_timeout
  
  sub_filter
  sub_filter_once
  sub_filter_types
  
  userid
  userid_domain
  userid_expires
  userid_name
  userid_p3p
  userid_path
  userid_service
  
  xml_entities
  xslt_stylesheet
  xslt_types
  
  js
  js_load
  js_require
  js_utf8
  
  echo
  echo_duplicate
  echo_flush
  echo_sleep
  echo_blocking_sleep
  echo_reset_timer
  echo_read_request_body
  echo_location_async
  echo_location
  echo_subrequest_async
  echo_subrequest
  echo_foreach_split
  echo_end
  echo_request_body
  echo_exec
  echo_before_body
  echo_after_body
  
  more_set_headers
  more_clear_headers
  more_set_input_headers
  more_clear_input_headers
  
  push_subscriber
  push_subscriber_concurrency
  push_publisher
  push_store_messages
  push_max_reserved_memory
  push_min_message_buffer_length
  push_max_message_buffer_length
  push_message_buffer_length
  push_min_message_recipients
  push_message_timeout
  push_authorized_channels_only
  push_channel_group
  push_max_channel_id_length
  push_max_channel_subscribers
}

js_reserved = %W{
  return
  break
  if
  else
  set
  get
}

puts keys.sort.map{|v| js_reserved.index(v) ? "'#{v}': 1" : "#{v}: 1"}.join(", ")